--------------------------------------------------------
--  File created - Wednesday-September-21-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CITYLIST
--------------------------------------------------------

  CREATE TABLE "HIBERNATE"."CITYLIST" 
   (	"ID" NUMBER, 
	"C_ID" NUMBER, 
	"S_ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COUNTRYLIST
--------------------------------------------------------

  CREATE TABLE "HIBERNATE"."COUNTRYLIST" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATELIST
--------------------------------------------------------

  CREATE TABLE "HIBERNATE"."STATELIST" 
   (	"ID" NUMBER, 
	"C_ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HIBERNATE.CITYLIST
SET DEFINE OFF;
Insert into HIBERNATE.CITYLIST (ID,C_ID,S_ID,NAME) values (1,1,1,'indore');
REM INSERTING into HIBERNATE.COUNTRYLIST
SET DEFINE OFF;
Insert into HIBERNATE.COUNTRYLIST (ID,NAME) values (1,'India');
Insert into HIBERNATE.COUNTRYLIST (ID,NAME) values (2,'pankistan');
REM INSERTING into HIBERNATE.STATELIST
SET DEFINE OFF;
Insert into HIBERNATE.STATELIST (ID,C_ID,NAME) values (1,1,'mp');
Insert into HIBERNATE.STATELIST (ID,C_ID,NAME) values (2,2,'KARACHI');
--------------------------------------------------------
--  DDL for Index CITYLIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HIBERNATE"."CITYLIST_PK" ON "HIBERNATE"."CITYLIST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COUNTRYLIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HIBERNATE"."COUNTRYLIST_PK" ON "HIBERNATE"."COUNTRYLIST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STATELIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HIBERNATE"."STATELIST_PK" ON "HIBERNATE"."STATELIST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CITYLIST
--------------------------------------------------------

  ALTER TABLE "HIBERNATE"."CITYLIST" ADD CONSTRAINT "CITYLIST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HIBERNATE"."CITYLIST" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HIBERNATE"."CITYLIST" MODIFY ("S_ID" NOT NULL ENABLE);
  ALTER TABLE "HIBERNATE"."CITYLIST" MODIFY ("C_ID" NOT NULL ENABLE);
  ALTER TABLE "HIBERNATE"."CITYLIST" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COUNTRYLIST
--------------------------------------------------------

  ALTER TABLE "HIBERNATE"."COUNTRYLIST" ADD CONSTRAINT "COUNTRYLIST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HIBERNATE"."COUNTRYLIST" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATELIST
--------------------------------------------------------

  ALTER TABLE "HIBERNATE"."STATELIST" ADD CONSTRAINT "STATELIST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HIBERNATE"."STATELIST" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HIBERNATE"."STATELIST" MODIFY ("C_ID" NOT NULL ENABLE);
  ALTER TABLE "HIBERNATE"."STATELIST" MODIFY ("ID" NOT NULL ENABLE);
